
export const CONFIRM_TIMESLOT = 'CONFIRM_TIMESLOT';
export const CONFIRM_TIMESLOT_SUCCESS = 'CONFIRM_TIMESLOT_SUCCESS';
export const CONFIRM_TIMESLOT_FAILURE = 'CONFIRM_TIMESLOT_FAILURE';
export const DELETE_TIMESLOT_SUCCESS = 'DELETE_TIMESLOT_SUCCESS';
export const DELETE_TIMESLOT_FAILURE = 'DELETE_TIMESLOT_FAILURE';